/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-12-09 03:56:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.dto.BoardDTO;
import poly.dto.B_CommentDTO;
import poly.util.CmmUtil;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/include/TopbarLoginAdmin.jsp", Long.valueOf(1575836319688L));
    _jspx_dependants.put("/WEB-INF/view/include/TopbarLogout.jsp", Long.valueOf(1575700325099L));
    _jspx_dependants.put("/WEB-INF/view/include/TopbarLoginUser.jsp", Long.valueOf(1575836260503L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("poly.util.CmmUtil");
    _jspx_imports_classes.add("poly.dto.BoardDTO");
    _jspx_imports_classes.add("poly.dto.B_CommentDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String userId = (String) session.getAttribute("userId");
	String user_Rights = CmmUtil.nvl((String) session.getAttribute("user_Rights")); //권한
	BoardDTO bDTO = (BoardDTO) request.getAttribute("bDTO");
	int seq = Integer.parseInt((String) request.getAttribute("seq"));
	String pgNum = (String) request.getAttribute("pgNum"); //pgNum을 가져옴

	List<B_CommentDTO> rList = (List<B_CommentDTO>) request.getAttribute("rList");
	if (rList == null) {
		rList = new ArrayList();
	}

	B_CommentDTO cDTO = (B_CommentDTO) request.getAttribute("cDTO");

	String no_seq = (String) request.getAttribute("no_seq");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\" class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Mobile Specific Meta -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Author Meta -->\r\n");
      out.write("<meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("<!-- Meta Description -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- Meta Keyword -->\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<!-- meta character set -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Site Title -->\r\n");
      out.write("<title>공지사항</title>\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"/css/modern-business.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--공통 css-->\r\n");
      out.write("<link href=\"/css/user-common.css\" rel=\"stylesheet\">\r\n");
      out.write("<!--추가 css-->\r\n");
      out.write("<link href=\"/css/user-board.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/main.css\">\r\n");
      out.write("<link href=\"/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/mypage.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- header -->\r\n");
      out.write("\t");

		if (userId == null) {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div class=\"header-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-6 header-top-left\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<!-- <li onclick=\"location.href='/main/llogin.do'\"  style=\"cursor: pointer;\"> -->\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/main/llogin.do\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/main/add.do\">회원가입</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/main/mypage.do\">마이페이지</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container main-menu\">\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/index.do\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: aliceblue; font-size: 2em;\">Electric vehicle</a>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/index.do\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"\">전기차 충전소</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/car/carFind.do\">주변 전기차 충전소 위치 및 검색</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/car/money.do\">국가보조금</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/board/board.do\">게시판</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/notice/notice.do\">공지사항</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		} else if (user_Rights.equals("1")) {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div class=\"header-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-6 header-top-left\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Logoutbtn.do\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/manager/page.do\">관리자 페이지</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container main-menu\">\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/index.do\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: aliceblue; font-size: 2em;\">Electric vehicle</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/index.do\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"/car/carFind.do\">전기차 충전소</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/car/carFind.do\">주변 전기차 충전소 위치 및 검색</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/car/money.do\">국가보조금</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/board/board.do\">게시판</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/notice/notice.do\">공지사항</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		} else {
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t<header id=\"header\">\n");
      out.write("\t\t<div class=\"header-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-6 header-top-left\">\n");
      out.write("\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t<!-- <li onclick=\"location.href='/main/llogin.do'\"  style=\"cursor: pointer;\"> -->\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/Logoutbtn.do\">로그아웃</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/main/mypage.do\">마이페이지</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"container main-menu\">\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"/index.do\"\n");
      out.write("\t\t\t\t\t\tstyle=\"color: aliceblue; font-size: 2em;\">Electric vehicle</a>\n");
      out.write("\t\t\t\t\t<!-- <a href=\"index.html\"><img src=\"img/logo.png\" alt=\"\" title=\"\" /></a> -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/index.do\">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"/car/carFind.do\">전기차 충전소</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/car/carFind.do\">주변 전기차 충전소 위치 및 검색</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/car/money.do\">국가보조금</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/board/board.do\">게시판</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/notice/notice.do\">공지사항</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write("\r\n");
      out.write("\t<!-- #header -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"about-banner3 relative\" style=\"margin-top: -57px;\">\r\n");
      out.write("\t\t<div class=\"overlay overlay-bg\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"about-content col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"text-white\" style=\"font-weight: lighter; font-size: xx-large;\">커뮤니티 게시판</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h4 class=\"mt-4 mb-3\">");
      out.print(bDTO.getTitle());
      out.write("</h4>\r\n");
      out.write("\t\t<div class=\"\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t");

				Date date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").parse(bDTO.getReg_dt());
				SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
			
      out.write("\r\n");
      out.write("\t\t\t");
      out.print(format1.format(date));
      out.write(" | <small>작성자 : ");
      out.print(bDTO.getReg_id());
      out.write("</small>\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div style=\"width: 100%; height: 350px;\">");
      out.print(bDTO.getContent());
      out.write("</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 댓글 영역 -->\r\n");
      out.write("\t\t<div class=\"container comment-bottom\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<!-- 댓글 작성 form 시작 -->\r\n");
      out.write("\t\t\t<form action=\"/commentAddProc.do\" method=\"POST\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<h6>댓글</h6>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(no_seq);
      out.write("\" name=\"no_seq\">\r\n");
      out.write("\t\t\t\t\t<textarea name=\"content\" id=\"\" cols=\"30\" rows=\"10\" class=\"col-md-12\" style=\"height: 100px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn board-btn form_control col-md-2\" style=\"float: right;\" value=\"등록\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<!-- 댓글 작성 form 종료 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				for (int i = 0; i < rList.size(); i++) {
			
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t        var bDisplay = true;\r\n");
      out.write("\t\t\t\t\t        function Display");
      out.print(rList.get(i).getCom_seq());
      out.write("() {\r\n");
      out.write("\t\t\t\t\t            var display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write(" = document.getElementById(\"display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write("\"); // 수정 버튼 클릭 전 보여 줄 댓글\r\n");
      out.write("\t\t\t\t\t            var display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write(" = document.getElementById(\"display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write("\"); // 수정 버튼 클릭 후 보여 줄 댓글\r\n");
      out.write("\t\t\t\t\t            if (display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display == 'none') {\r\n");
      out.write("\t\t\t\t\t            \tdisplay_1_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display = 'none'; //보여지는거랑 숨겨진거랑 바꿔줌\r\n");
      out.write("\t\t\t\t\t            \tdisplay_2_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display = 'block';\r\n");
      out.write("\t\t\t\t\t            } else {\r\n");
      out.write("\t\t\t\t\t            \tdisplay_2.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t            }\r\n");
      out.write("\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t        //취소하기\r\n");
      out.write("\t\t\t\t\t        function Display_2");
      out.print(rList.get(i).getCom_seq());
      out.write("() {\r\n");
      out.write("\t\t\t\t\t            var display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write(" = document.getElementById(\"display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write("\"); // 수정 버튼 클릭 전 보여 줄 댓글\r\n");
      out.write("\t\t\t\t\t            var display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write(" = document.getElementById(\"display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write("\"); // 수정 버튼 클릭 후 보여 줄 댓글\r\n");
      out.write("\t\t\t\t\t\t\t\tif (display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display == 'none') {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdisplay_2_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdisplay_1_");
      out.print(rList.get(i).getCom_seq());
      out.write(".style.display = 'block';\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdisplay_1.style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t                // 댓글 수정 완료 버튼\r\n");
      out.write("\t\t\t                function Modify");
      out.print(rList.get(i).getCom_seq() );
      out.write("(){\r\n");
      out.write("\t\t\t                \tif (confirm(\"댓글을 수정하시겠습니까?\") == true) {\r\n");
      out.write("\t\t\t                    document.location.href = \"/commentModify.do?com_seq=\"+");
      out.print(rList.get(i).getCom_seq() );
      out.write("\r\n");
      out.write("\t\t\t                    +\"&no_seq=\"+");
      out.print(rList.get(i).getNo_seq());
      out.write("\r\n");
      out.write("\t\t\t                    +\"&content=\"+$(\"#content\"+");
      out.print(rList.get(i).getCom_seq() );
      out.write(").val();\r\n");
      out.write("\t\t\t                    return true;\r\n");
      out.write("\t\t\t                    } else {\r\n");
      out.write("\t\t\t                    \treturn false;\r\n");
      out.write("\t\t\t                    }\r\n");
      out.write("\t\t\t                 }\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 댓글 리스트 form 시작 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 숨겨져 있는 수정 부분 시작 -->\r\n");
      out.write("\t\t\t<div id=\"display_2_");
      out.print(rList.get(i).getCom_seq());
      out.write("\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 user-comment\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getNo_seq());
      out.write("\" name=\"no_seq\"> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getCom_seq());
      out.write("\" name=\"com_seq\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 col-md-offset-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 댓글 수정 textarea 부분 시작 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"forumText forumMax col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" value=\"");
      out.print(rList.get(i).getContent());
      out.write("\" name=\"content");
      out.print(rList.get(i).getCom_seq());
      out.write("\" id=\"content");
      out.print(rList.get(i).getCom_seq());
      out.write("\" class=\"comment-st\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn comment-btn-free\" value=\"완료\" onclick=\"Modify");
      out.print(rList.get(i).getCom_seq());
      out.write("()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:Display_2");
      out.print(rList.get(i).getCom_seq());
      out.write("();\" class=\"btn comment-btn-free\">취소</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"forumTagline col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"forumName text-muted\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(rList.get(i).getUser_id());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(rList.get(i).getReg_dt().substring(2, 16));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 0rem;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 숨겨져 있는 수정 부분 종료 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 기존 댓글이 보여줄 부분 display:block로 보여줌, 수정 버튼 클릭 시  javascript로 인해 display:none으로 바뀜  시작-->\r\n");
      out.write("\t\t\t<!-- 댓글 리스트 -->\r\n");
      out.write("\t\t\t<div id=\"display_1_");
      out.print(rList.get(i).getCom_seq());
      out.write("\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getNo_seq());
      out.write("\" name=\"no_seq\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getCom_seq());
      out.write("\" name=\"com_seq\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12 col-md-offset-0\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p style=\"height: 30px;\">");
      out.print(rList.get(i).getContent());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (userId != null) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (rList.get(i).getUser_id().equals(userId)) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getCom_seq());
      out.write("\" name=\"com_seq\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(rList.get(i).getNo_seq());
      out.write("\" name=\"no_seq\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:Display");
      out.print(rList.get(i).getCom_seq());
      out.write("();\" class=\"btn\">수정</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"/commentDelete.do?com_seq=");
      out.print(rList.get(i).getCom_seq());
      out.write("&no_seq=");
      out.print(rList.get(i).getNo_seq());
      out.write("\" class=\"btn comment-btn-free\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(rList.get(i).getUser_id());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(rList.get(i).getReg_dt().substring(2, 16));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<hr style=\"margin-top: 0rem; margin-bottom: 0.5rem;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 기존 댓글이 보여줄 부분 display:block로 보여줌, 수정 버튼 클릭 시  javascript로 인해 display:none으로 바뀜  종료-->\r\n");
      out.write("\t\t\t<!-- 댓글 리스트 form 종료 -->\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /댓글 영역 -->\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if (user_Rights.equals("0") || user_Rights.equals("1")) {
		
      out.write("\r\n");
      out.write("\t\t<div class=\"board-btn\">\r\n");
      out.write("\t\t\t<div style=\"display: inline-block;\">\r\n");
      out.write("\t\t\t\t<a href=\"/board/board.do?pgNum=");
      out.print(pgNum);
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"genric-btn primary-border medium\">목록</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"display: inline-block; margin-left: 64%;\">\r\n");
      out.write("\t\t\t\t<a href=\"/board/boardModify.do?seq=");
      out.print(seq);
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"genric-btn success-border medium\">수정하기</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"/board/BoardDelete.do?seq=");
      out.print(seq);
      out.write("\"\r\n");
      out.write("\t\t\t\t\tclass=\"genric-btn success-border medium\">삭제하기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End hot-deal Area -->\r\n");
      out.write("\t<script src=\"/js/vendor/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA\"></script>\r\n");
      out.write("\t<script src=\"/js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script src=\"/js/easing.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/hoverIntent.js\"></script>\r\n");
      out.write("\t<script src=\"/js/superfish.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"/js/mail-script.js\"></script>\r\n");
      out.write("\t<script src=\"/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
